### ISSUE TITLE
최초로 맞은 문제에 한하여 웹훅이 전송되는 기능을 추가

### ISSUE THREAD

**Issue by wzrabbit** [BaekjoonCord/BJCORD-extension#39]
BJCORD에서 **최초로 문제를 맞춘 경우에 한하여** 웹훅을 전송하는 기능이 추가되었으면 좋겠습니다. 이 기능을 구상하게 된 계기는 아래와 같습니다.

- 다른 사람의 질문 해결을 위해 다른 사람의 코드를 디버깅하여 제출하는 경우가 간혹 있습니다. 이 경우 실제로 새로운 문제를 푼 것이 아닌데, 웹훅 내역에 모두 보여지면 지저분할 것 같다는 생각이 들었습니다.
- 스스로 코드를 개선하기 위해 이미 맞춘 이후에도 재제출하는 경우가 있으며, 데이터 확인을 위해 검증 코드를 작성해 재제출하는 등 여러 재제출 사례가 존재합니다.

개인적으로 스터디 등을 진행하든, 개인적인 용도로든 새로운 문제를 풀었을 때에만 이러한 알림이 가도록 하도록 동작했으면 좋겠다는 생각이 들었고, 이 방향으로 프로그램이 작동하기를 원하시는 스터디 관리자분들도 계실 것이라고 생각합니다.
허나 BJCORD의 기획에 맞지 않을 수도 있고, 재제출을 하더라도 웹훅 전송을 원하시는 분들도 계실 것이라고 생각하기에, 어느 한쪽으로 동작하는 것을 강제하는 것 보다는, **이미 맞춘 문제여도 웹훅으로 전송할 지를 결정할 수 있도록** 하는 기능이 있으면 좋을 것이라고 생각합니다.

**Comment by 5tarlight** [comment]
안녕하세요. 제안해 주신 내용은 BJCORD의 기획 의도와 여러 장점을 한번에 잡은 좋은 제안으로 생각합니다.

https://github.com/BaekjoonCord/BJCORD-extension/blob/157e06056ce6f5fae2724cb75ba07bdcac9fdc2a/scripts/content/boj.js#L72-L77

시도 횟수를 세는 로직을 변경해 간단히 구현할 수 있을 것으로 보입니다. BOJ의 "내 채점" 테이블에서 데이터를 가져오는 BJCORD의 특성상 한 페이지가 전부 AC가 아닌 다른 결과로 도배된다면 최초로 맞았는지 검토할 수 없지만 일반적인 경우는 아니니 큰 문제는 없을 것 같습니다.

이번 제안을 향후 업데이트에 반영할 수 있도록 하겠습니다. 프로젝트에 관심을 가져 주셔서 감사드립니다!

**Comment by wzrabbit** [comment]
오, 빠르게 답변해 주셔서 감사합니다. 하지만 제가 이미 PR을 올려둔 상태입니다. 이 이슈도 PR을 올리기 위해 적은 것에 가깝습니다! 말씀하신 방법을 사용하실 수도 있겠습니다만 PR도 한 번 구경해주실 수 있나요? 감사합니다.
